### ISSUE TITLE
Problems with imports

### ISSUE THREAD

**Issue by Anonym0u5** [CodyEngel/Hello-Glass#2]
Hello,
Do you know why this happens?
https://www.dropbox.com/s/9oh3qxvp0v2s9jp/Screenshot%202014-04-25%2000.42.26.png

Which library(ies) I should add to my project?

**Comment by CodyEngel** [comment]
Which build target do you have selected? Make sure the Glass Development Kit Sneak Peek is selected.

http://i.imgur.com/cyYIvgY.png

**Comment by CodyEngel** [comment]
I'm going to assume this issue was resolved.
